import { test, expect } from "./support/account-fixture";
import AxeBuilder from "@axe-core/playwright";
import type { Page } from "@playwright/test";
const password = "Sample meadow password 42!";
async function register(page: Page) {
  await page.goto("/");
  await page.getByRole("button", { name: "Create your workspace" }).click();
  await page.getByLabel("Your name").fill("Jamie");
  await page.getByLabel("Email address").fill("jamie@example.edu");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByLabel("Confirm password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  const code = await page.getByLabel("Recovery code", { exact: true }).textContent();
  await expect(page.getByRole("button", { name: "Continue", exact: true })).toBeDisabled();
  await page.getByLabel("I saved my recovery code").check();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("button", { name: "Looks good" }).click();
  await page.getByRole("button", { name: "I’ll do this later" }).click();
  await page.getByRole("button", { name: "Let’s begin" }).click();
  await expect(page.getByRole("heading", { name: /Good .*Jamie/ })).toBeVisible();
  return code!;
}
test("account changes, invalid current password, recovery rotation and deletion", async ({ page }) => {
  const code = await register(page);
  const stored = await page.evaluate(() => JSON.stringify({ ...localStorage, ...sessionStorage }));
  expect(stored).not.toContain(password); expect(stored).not.toContain(code); expect(stored).not.toContain('"user":');
  await page.goto("/settings");
  await page.getByRole("button", { name: "Edit account", exact: true }).click();
  await page.getByLabel("Your name").fill("Jamie Lee");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Account details saved.");
  await page.getByRole("button", { name: "Change password", exact: true }).click();
  await page.getByLabel("Current password").fill("wrong password");
  await page.getByLabel("New password", { exact: true }).fill("Changed meadow password 43!");
  await page.getByLabel("Confirm new password").fill("Changed meadow password 43!");
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("alert")).toHaveText("Your current password is incorrect.");
  await page.getByLabel("Current password").fill(password);
  await page.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Password changed");
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await page.getByRole("button", { name: "I already have an account" }).click();
  await page.getByRole("button", { name: "Forgot your password?" }).click();
  await page.getByLabel("Email address").fill("jamie@example.edu");
  await page.getByLabel("Recovery code", { exact: true }).fill("invalid-code");
  await page.getByLabel("New password", { exact: true }).fill("Recovered meadow password 44!");
  await page.getByLabel("Confirm password", { exact: true }).fill("Recovered meadow password 44!");
  await page.getByRole("button", { name: "Reset password", exact: true }).click();
  await expect(page.getByRole("alert")).toHaveText("Email or recovery code is incorrect.");
  await page.getByLabel("Recovery code", { exact: true }).fill(code);
  await page.getByRole("button", { name: "Reset password", exact: true }).click();
  await expect(page.getByLabel("Recovery code", { exact: true })).not.toHaveText(code);
  await page.getByLabel("I saved my recovery code").check();
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Password reset");
  await page.getByLabel("Password", { exact: true }).fill("Recovered meadow password 44!");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.goto("/settings");
  await page.getByRole("button", { name: "Delete account", exact: true }).click();
  await page.getByLabel("Current password").fill("Recovered meadow password 44!");
  await page.getByLabel("I understand that deletion is permanent").check();
  await page.getByRole("button", { name: "Permanently delete account", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Welcome to your space." })).toBeVisible();
});
test("account forms fit narrow screens, report mismatches, and recovery code remains visible until saved", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Create your workspace" }).click();
  await page.getByLabel("Your name").fill("Jamie");
  await page.getByLabel("Email address").fill("jamie@example.edu");
  await page.getByLabel("Password", { exact: true }).fill(password);
  await page.getByLabel("Confirm password", { exact: true }).fill("different password");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await expect(page.getByRole("alert")).toHaveText("Passwords do not match.");
  await page.getByLabel("Confirm password", { exact: true }).fill(password);
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  for (const width of [375, 768, 1440]) {
    await page.setViewportSize({ width, height: 950 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  }
  const results = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(results.violations).toEqual([]);
});
test("replacement recovery code cannot be dismissed before acknowledgement", async ({ page }) => {
  await register(page);
  await page.goto("/settings");
  await page.getByRole("button", { name: "Replace recovery code", exact: true }).click();
  await page.getByLabel("Current password").fill(password);
  await page.getByRole("button", { name: "Generate replacement code", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Your new recovery code" });
  await expect(dialog).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole("button", { name: "Close", exact: true })).toBeDisabled();
  await dialog.getByLabel("I saved my recovery code").check();
  await dialog.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(dialog).not.toBeVisible();
});
